---
- name: Generate/Update custom vars file.
  include_tasks: allowed_vars.yml
  when:
    - ce_provision.extra_repository
    - ce_provision.extra_repository_vars_file

- name: Store current playbook md5.
  copy:
    content: "{{ current_play_dir_md5.stdout }}"
    dest: "{{ _ce_provision_data_dir }}/{{ current_play_md5_file }}"
  delegate_to: localhost
