---

  - set_fact:
      ansible_provision_extra_vars_computed: "{{ ansible_provision_extra_vars_computed | default({}) | combine({item.name: lookup('vars', item.name)}, recursive=True) }}"
    when:
      - ansible_provision.extra_repository
      - ansible_provision.extra_repository_vars_file
      - ansible_provision.extra_repository_allowed_vars is defined
      - lookup('vars', item.name, default=null)
    loop: "{{ ansible_provision.extra_repository_allowed_vars }}"
  
  - name: Generate/Update custom vars file.
    local_action:
      module: template
      src: vars.j2
      dest: "{{ _ansible_provision_build_tmp_dir }}/extra/{{ ansible_provision.extra_repository_vars_file }}"
    when: ansible_provision_extra_vars_computed is defined
  
  - name: Stat newly generated configuration.
    local_action:
      module: command
      cmd: git add .
      args: 
        chdir: "{{ _ansible_provision_build_tmp_dir }}/extra"
    when: ansible_provision_extra_vars_computed is defined

  - name: Commit newly generated configuration.
    local_action:
      module: command
      cmd: "git commit - m 'Ansible autogenerated configuration export - {{ ansible_date_time.iso8601 }}'"
      args: 
        chdir: "{{ _ansible_provision_build_tmp_dir }}/extra"
    when: ansible_provision_extra_vars_computed is defined
  
  - name: Push newly generated configuration.
    local_action:
      module: command
      cmd: "git push origin {{ ansible_provision.extra_repository_branch }}"
      args:
        chdir: "{{ _ansible_provision_build_tmp_dir }}/extra"
    when: ansible_provision_extra_vars_computed is defined