---
- name: Add repository key for Gitlab.
  apt_key:
    url: https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
    state: present

- name: Add repository for Gitlab.
  apt_repository:
    repo: "deb https://packages.gitlab.com/gitlab/gitlab-ce/debian/ buster main"
    state: present

- name: Add source repository for Gitlab.
  apt_repository:
    repo: "deb-src https://packages.gitlab.com/gitlab/gitlab-ce/debian/ buster main"
    state: present

- name: Ensure Gitlab is installed.
  apt:
    pkg: "gitlab-ce"
    state: present
    update_cache: true

- name: Generates SSL keys.
  include_role:
    name: ssl
  when: gitlab.ssl is defined
  vars:
    ssl: "{{ gitlab.ssl | combine( { 'domain': gitlab.server_name } ) }}"

- name: Copy Gitlab configuration file.
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb

- name: Let Gitlab know it's on Docker.
  copy:
    content: "gitlab-docker"
    dest: "/opt/gitlab/embedded/service/gitlab-rails/INSTALLATION_TYPE"
    mode: "0666"
  when:
    - is_local is defined
    - is_local

- name: Copy startup script in place.
  template:
    src: docker-init.sh.j2
    dest: "/opt/gitlab-init.sh"
    owner: root
    group: root
    mode: "0555"
    force: true
  when:
    - is_local is defined
    - is_local

- name: Trigger overrides
  include_role:
    name: _overrides
  vars:
    _overrides: "{{ gitlab.overrides }}"
  when:
    - gitlab.overrides is defined
    - gitlab.overrides | length > 0

- name: Manually restart Gitlab/Docker.
  command: "/bin/sh /opt/gitlab-init.sh"
  when:
    - is_local is defined
    - is_local

- name: Stop Gitlab.
  command: /opt/gitlab/bin/gitlab-ctl stop

- name: Reconfigure Gitlab.
  command: /opt/gitlab/bin/gitlab-ctl reconfigure

- name: Restart Gitlab.
  command: /opt/gitlab/bin/gitlab-ctl start

- name: Disable self-register feature
  command: "gitlab-rails runner 'ApplicationSetting.last.update_attributes(signup_enabled: false)'"

- name: Disable DSA keys
  command: "gitlab-rails runner 'ApplicationSetting.last.update_attributes(dsa_key_restriction: -1)'"

- name: Disable ECDSA
  command: "gitlab-rails runner 'ApplicationSetting.last.update_attributes(ecdsa_key_restriction: -1)'"

- name: Enforce at least 2048bits for RSA
  command: "gitlab-rails runner 'ApplicationSetting.last.update_attributes(rsa_key_restriction: 2048)'"

- name: Disable password auth over HTTP/S
  command: "gitlab-rails runner 'ApplicationSetting.last.update_attributes(password_authentication_enabled_for_git: false)'"
