---

- name: Ensure nginx is installed.
  apt:
    pkg: nginx
    state: present
    update_cache: yes
    cache_valid_time: 240

- name: Generates SSL keys.
  include_role:
    name: "{{ item.ssl_handling }}"
  vars:
    ssl:
      domain: "{{ item.server_name }}"
      services: ['nginx']
  with_items: "{{ nginx.domains }}"

- name: Copy maing nginx config.
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
  
- name: Copy vhosts in place.
  template:
    src: vhosts.j2
    dest: "/etc/nginx/sites-available/{{ domain.server_name }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ nginx.domains }}"
  loop_control:
    loop_var: domain

- name: Enable vhosts.
  file:
    src: "/etc/nginx/sites-available/{{ domain.server_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ domain.server_name }}.conf"
    state: link
  with_items: "{{ nginx.domains }}"
  loop_control:
    loop_var: domain

- name: Copy project type-specific configuration in place.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nginx/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
    force: yes
  with_items:
    - _common
    - custom
    - docker_registry
    - drupal_common
    - drupal7
    - drupal8
    - flat
    - matomo
    - mautic
    - simplesamlphp
    - symfony3
    - symfony4
    - wordpress

- name: Ensure default nginx catch-all is not present
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Generates AWS Cloudwatch default config.
  template:
    src: cloudwatch-main.json.j2
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/nginx-main.json
  when:
    - is_local is not defined or not is_local

- name: Generates AWS Cloudwatch vhosts config.
  template:
    src: cloudwatch-vhost.json.j2
    dest: "/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/nginx-{{ domain.server_name }}.json"
  when:
    - not domain.access_log == "/var/log/nginx/access.log"
    - not domain.error_log == "/var/log/nginx/error.log"
    - is_local is not defined or not is_local
  with_items: "{{ nginx.domains }}"
  loop_control:
    loop_var: domain

- name: Trigger overrides
  include_role: 
    name: _overrides

- name: Ensure Nginx is restarted.
  service:
    name: nginx
    state: restarted