---

- name: Ensure nginx is installed.
  apt:
    name:
      - nginx
      - python-passlib
    state: present
    update_cache: yes
    cache_valid_time: 240

- name: Copy main nginx config.
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644

- name: Ensure passwords directory exists.
  file:
    path: /etc/nginx/passwords
    state: directory
    mode: '0755'

- name: Copy project type-specific configuration in place.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nginx/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
    force: yes
  with_items:
    - _common
    - custom
    - docker_registry
    - drupal_common
    - drupal7
    - drupal8
    - flat
    - matomo
    - mautic
    - simplesamlphp
    - symfony3
    - symfony4
    - wordpress

- name: Ensure default nginx catch-all is not present
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Generates AWS Cloudwatch default config.
  template:
    src: cloudwatch-main.json.j2
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/nginx-main.json
  when:
    - is_local is not defined or not is_local

- name: Generate domain specific configuration.
  include_tasks: domain.yml
  with_items: "{{ nginx.domains }}"
  loop_control:
    loop_var: domain

- name: Trigger overrides
  include_role: 
    name: _overrides

- name: Ensure Nginx is restarted.
  service:
    name: nginx
    state: restarted