- name: Print Security Group to screen.
  ansible.builtin.debug:
    var: security_group

- name: Create Security Group.
  ec2_group:
    name: "{{ security_group.name }}"
    profile: "{{ aws_vpc.aws_profile }}"
    region: "{{ aws_vpc.region }}"
    tags: "{{ aws_vpc.tags | combine({ 'Name': security_group.name }) }}"
    state: "{{ aws_vpc.state }}"
    vpc_id: "{{ _aws_vpc_vpc.vpc.id }}"
    description: "{{ security_group.description }}"
    rules: "{{ security_group.rules }}"
    rules_egress: "{{ security_group.rules_egress | default(omit) }}"
  register: this_group
  
- name: Show stdout for group creation.
  ansible.builtin.debug:
    var: this_group.stdout
