# @todo Once the ec2_eip module is fixed, we can get rid of most of the logic below.
# For now, we register and manually tag the EIP with ec2_tag.
- name: Check if we have an EIP already.
  ec2_eip_info:
    profile: "{{ aws_vpc_with_subnets.aws_profile }}"
    region: "{{ aws_vpc_with_subnets.region }}"
    filters:
      tag:Name: "{{ subnet.tags.Name }}"
  register: _aws_vpc_with_subnets_eip

- name: Create the NAT gateway.
  ec2_vpc_nat_gateway:
    profile: "{{ aws_vpc_with_subnets.aws_profile }}"
    region: "{{ aws_vpc_with_subnets.region }}"
    tags: "{{ aws_vpc_with_subnets.tags | combine({ 'Name': subnet.tags.Name }) }}"
    subnet_id: "{{ subnet.subnet_id }}"
    wait: yes
    allocation_id: "{{ _aws_vpc_with_subnets_eip.addresses[0].allocation_id | default(omit) }}"
    if_exist_do_not_create: yes
  register: _aws_vpc_with_subnets_gateway

- name: Ensure EIP is tagged properly.
  ec2_tag:
      resource: "{{ _aws_vpc_with_subnets_gateway.nat_gateway_addresses[0].allocation_id }}"
      tags: "{{ aws_vpc_with_subnets.tags | combine({ 'Name': subnet.tags.Name }) }}"
      profile: "{{ aws_vpc_with_subnets.aws_profile }}"
      region: "{{ aws_vpc_with_subnets.region }}"
    
- name: Update route table.
  include_role:
    name: aws/aws_vpc_route
  vars:
    aws_vpc_route:
      aws_profile: "{{ aws_vpc_with_subnets.aws_profile }}"
      region: "{{ aws_vpc_with_subnets.region }}"
      vpc_id: "{{ _aws_vpc_with_subnets_vpc.vpc.id }}"
      subnet_id: "{{ subnet.subnet_id }}"
      tags: "{{ aws_vpc_with_subnets.tags | combine({ 'Name': subnet.tags.Name }) }}"
      routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ _aws_vpc_with_subnets_gateway.nat_gateway_id }}"