- name: Create IGW
  ec2_vpc_igw:
    profile: "{{ aws_vpc_with_subnets.aws_profile }}"
    region: "{{ aws_vpc_with_subnets.region }}"
    vpc_id: "{{ _aws_vpc_with_subnets_vpc.vpc.id }}"
    state: present
    tags: "{{ aws_vpc_with_subnets.tags | combine({ 'Name': aws_vpc_with_subnets.name }) }}"
  register: _aws_vpc_with_subnets_gateway

- name: Update Main route table.
  include_role:
    name: aws/aws_vpc_route
  vars:
    aws_vpc_route:
      aws_profile: "{{ aws_vpc_with_subnets.aws_profile }}"
      region: "{{ aws_vpc_with_subnets.region }}"
      vpc_id: "{{ _aws_vpc_with_subnets_vpc.vpc.id }}"
      tags: "{{ aws_vpc_with_subnets.tags }}"
      routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ _aws_vpc_with_subnets_gateway.gateway_id }}"