- name: Create VPC.
  ec2_vpc_net:
    profile: "{{ aws_vpc_with_subnets.aws_profile }}"
    name: "{{ aws_vpc_with_subnets.name }}"
    cidr_block: "{{ aws_vpc_with_subnets.cidr_block }}"
    region: "{{ aws_vpc_with_subnets.region }}"
    tags: "{{ aws_vpc_with_subnets.tags }}"
    state: "{{ aws_vpc_with_subnets.state }}"
  register: _aws_vpc_with_subnets_vpc

- name: Create VPC subnets.
  include_tasks: "subnet.yml"
  with_items: "{{ aws_vpc_with_subnets.subnets }}"
  loop_control:
    loop_var: subnet

- name: Create VPC Security groups.
  include_tasks: "security_group.yml"
  with_items: "{{ aws_vpc_with_subnets.security_groups }}"
  loop_control:
    loop_var: security_group

- name: Create VPC IGW.
  include_tasks: "igw.yml"

- name: Gather Subnets information
  ec2_vpc_subnet_info:
    profile: "{{ aws_vpc_with_subnets.aws_profile }}"
    region: "{{ aws_vpc_with_subnets.region }}"
    filters:
      vpc-id: "{{ _aws_vpc_with_subnets_vpc.vpc.id }}"
  register: _aws_vpc_with_subnets_subnets
  when: aws_vpc_with_subnets.nat_ipv4

- name: Create VPC ipv4 gateway.
  include_tasks: "gateway.ipv4.nat.yml"
  with_items: "{{ _aws_vpc_with_subnets_subnets.subnets }}"
  loop_control:
    loop_var: subnet
  when: aws_vpc_with_subnets.nat_ipv4