---

- name: Generate Name tag.
  set_fact:
    _vpc_security_group_name: "{{ aws_vpc_with_subnets.name }}-{{ security_group.name }}"

- name: Create Security Group.
  ec2_group:
    name: "{{ _vpc_security_group_name }}"
    profile: "{{ aws_vpc_with_subnets.aws_profile }}"
    region: "{{ aws_vpc_with_subnets.region }}"
    tags: "{{ aws_vpc_with_subnets.tags }}"
    state: "{{ aws_vpc_with_subnets.state }}"
    vpc_id: "{{ _ec2_vpc_created.vpc.id }}"
    description: "{{ security_group.description }}"
    rules: "{{ security_group.rules }}"
    rules_egress: "{{ security_group.rules_egress | default(omit) }}"