---

- name: Generate Name tag.
  set_fact:
    _vpc_subnet_name_tag: { Name: "{{ aws_vpc_with_subnets.name }}-{{ subnet.az }}"}

- name: Generate subnet tags.
  set_fact:
    _vpc_subnet_tags: "{{ aws_vpc_with_subnets.tags | combine(_vpc_subnet_name_tag) }}"


- name: Create VPC subnet.
  ec2_vpc_subnet:
    profile: "{{ aws_vpc_with_subnets.aws_profile }}"
    cidr: "{{ subnet.cidr }}"
    region: "{{ aws_vpc_with_subnets.region }}"
    tags: "{{ _vpc_subnet_tags }}"
    az: "{{ aws_vpc_with_subnets.region }}{{ subnet.az }}"
    state: "{{ subnet.state }}"
    vpc_id: "{{ _ec2_vpc_created.vpc.id }}"
    assign_instances_ipv6: "{{ subnet.assign_instances_ipv6 }}"