addons:
  apt:
    packages:
    - git
    - ansible
script:
  - cp install/example.vars.yml install/vars.yml
  - sed -i "s/ \"provision\"/ $(whoami)/g" install/vars.yml
  - ansible-playbook install/self-update.yml --extra-vars="@install/vars.yml"