ce-provision-1.x-travis:
  src: https://github.com/codeenigma/ce-provision.git
  src_branch: 1.x
  src_subdir: 'docs'
  dest: https://${{ secrets.DOCS_GITHUB_TOKEN }}@github.com/codeenigma/ce-provision-docs.git
  dest_branch: master
  dest_subdir: 1.x
  title: ce-provision
  type: doc
  base_url: https://codeenigma.github.io/ce-provision-docs/1.x
