---
dependencies:
  - role: locales
  - role: user_root
  - role: apt_extra_packages
  - { role: apt_extra_packages, apt_extra_packages: ["rsync", "python-apt"] }
  - { role: hosts, when: ( is_local is not defined or not is_local ) }
  - role: rkhunter
  - role: postfix
