---
aws_ec2_metric_alarm:
  aws_profile: "{{ _aws_profile }}"
  region: "{{ _aws_region }}"
  state: present
  name: ""
  description: ""
  metric: ""
  namespace: "" # The CloudWatch namespace (category) the alarm will appear in.
  statistic: "Average" # Statistical model to apply to the values gathered.
  comparison: ""
  threshold: 75.0 # The min/max bound for triggering the alarm.
  unit: "Seconds" # The threshold's unit of measurement.
  period: 2 # The time (in seconds) between metric evaluations.
  evaluation_periods: 2 # The number of times the metric is calculated before final calculation.
  dimensions: [] # List of metrics the alarm is applied to.
  alarm_actions: [] # List of ARNs of actions to take if the alarm is triggered.
  insufficient_data_actions: [] # List of ARNs of actions to take if the alarm has insufficient data.
  ok_actions: [] # List of ARNs of actions to take if the alarm is in an OK state.
  treat_missing_data: "ignore" # What to do if data is missing (see API docs for options).
