---
- name: Gather EFS information.
  efs_info:
    profile: "{{ aws_efs_client.aws_profile }}"
    region: "{{ aws_efs_client.region }}"
    name: "{{ mount.src }}"
  become: yes
  become_user: "{{ user_provision.username }}"
  delegate_to: "{{ user_provision.utility_host }}"
  register: aws_efs_client_efs_volume

- name: Create fstab entry.
  mount:
    fstype: efs
    opts: "{{ mount.opts }}"
    src: "{{ aws_efs_client_efs_volume.efs[0].filesystem_address }}"
    path: "{{ mount.path }}"
    state: "{{ mount.state }}"
