---
- name: Install JRE/JDK packages.
  apt:
    pkg:
      - "openjdk-{{ openjdk.version }}-jre"
      - "openjdk-{{ openjdk.version }}-jdk"
    state: present
    update_cache: yes
    cache_valid_time: 240
