---
- name: Check if we already have an AWS cli bin.
  stat:
    path: "/usr/local/bin/aws"
  register: aws_cli_bin

- name: Fetch and extract AWS cli.
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp
    remote_src: true
  when:
    - not aws_cli_bin.stat.exists

- name: Install AWS cli.
  command:
    cmd: /tmp/aws/install --install-dir /opt/aws-cli --bin-dir /usr/local/bin
  when:
    - not aws_cli_bin.stat.exists
