---
php:
  version:
    - 7.3
symfony_env: "{{ env_type }}"
nginx:
  # Global default config for nginx.conf.
  user: www-data
  worker_processes: auto
  events:
    worker_connections: 768
  http:
    server_names_hash_bucket_size: 256
    access_log: /var/log/nginx-access.log
    error_log: /var/log/nginx-error.log
  # We can only have one backend, due to the way we use "common" templates.
  # Moving this per domain means instead having templates per project type.
  php_fastcgi_backend: "127.0.0.1:90{{ php.version[-1] | replace('.','') }}"
  ratelimitingcrawlers: false
  client_max_body_size: "700M"
  domains:
    - server_name: "{{ domain_name }}"
      access_log: "/var/log/nginx/access.log"
      error_log: "/var/log/nginx/error.log"
      error_log_level: "notice"
      webroot: "/var/www/html"
      project_type: "flat"
      ssl: # @see the 'ssl' role.
        domain: "{{ domain_name }}"
        handling: selfsigned
      ratelimitingcrawlers: true
      is_default: true
      basic_auth:
        auth_enabled: true
        auth_user: "{{ project_name }}"
        auth_pass: "P3nguin!"
      servers:
        - port: 80
          ssl: false
          https_redirect: true
        - port: 443
          ssl: true
          https_redirect: false
      upstreams: []
      # upstreams:
      #   - name: 'backend_example'
      #     backends:
      #       - 142.42.64.2:8080
      #       - 142.42.64.3:8080
