---
- name: Set "tracking" file for the playbook.
  set_fact:
    current_play_md5_file: "{{ _ce_provision_build_id }}-{{ playbook_dir | basename }}-{{ inventory_hostname }}"

- name: Sanitize tracking file name.
  set_fact:
    current_play_md5_file: "{{ current_play_md5_file | regex_replace('[^A-z0-9]', '') }}"

- name: Make sure file exists.
  copy:
    content: ""
    dest: "{{ _ce_provision_data_dir }}/{{ current_play_md5_file }}"
    force: false
    mode: "0666"
  delegate_to: localhost

- name: Build the list of directories to scan for changes.
  set_fact:
    _init_vars_dirs_list: "{{ _init.vars_dirs + [ playbook_dir | basename ] }}"

- name: Compute current playbook md5
  shell: 'find {{ _init_vars_dir }} -type f -exec md5sum {} \; | cut -d " " -f1 | md5sum'
  args:
    warn: false
  delegate_to: "localhost"
  register: _init_vars_dirs_md5
  with_items: "{{ _init_vars_dirs_list }}"
  loop_control:
    loop_var: _init_vars_dir

- name: Lookup current playbook md5
  set_fact:
    previous_play_dir_md5: "{{ lookup('file', '{{ _ce_provision_data_dir }}/{{ current_play_md5_file }}' ) }}"

- meta: end_play
  when:
    - current_play_dir_md5.stdout == previous_play_dir_md5
    - not _ce_provision_force_play

- name: Include vars directories.
  include_vars:
    dir: _init_vars_dir_include
    extensions:
      - "yml"
  with_items: "{{ _init.vars_dirs }}"
  loop_control:
    loop_var: _init_vars_dir

- name: Ensure /opt/bin directory exists.
  file:
    path: "/opt/bin"
    state: directory

- name: Clone custom extra directory.
  git:
    repo: "{{ ce_provision.extra_repository }}"
    dest: "{{ _ce_provision_build_tmp_dir }}/extra"
    version: "{{ ce_provision.extra_repository_branch }}"
  delegate_to: localhost
  when: ce_provision.extra_repository

- name: Include custom variables.
  include_vars:
    file: "{{ _ce_provision_build_tmp_dir }}/extra/{{ ce_provision.extra_repository_vars_file }}"
    name: _ce_provision_extra_vars
  when:
    - ce_provision.extra_repository
    - ce_provision.extra_repository_vars_file

- name: Filter allowed custom variables.
  set_fact:
    ce_provision_extra_vars_filtered: "{{ _ce_provision_extra_vars | allowed_vars(ce_provision.extra_repository_allowed_vars) }}"
  when:
    - ce_provision.extra_repository
    - ce_provision.extra_repository_vars_file
    - ce_provision.extra_repository_allowed_vars

- name: Override variables with custom ones.
  set_fact:
    "{{ item.name }}": "{{ ce_provision_extra_vars_filtered[item.name] }}"
  when:
    - ce_provision_extra_vars_filtered is defined
    - ce_provision_extra_vars_filtered[item.name] is defined
  loop: "{{ ce_provision.extra_repository_allowed_vars }}"

- name: Define template lookup paths.
  set_fact:
    ce_provision_search_paths_template:
      - "{{ playbook_dir }}/templates"
      - "{{ _ce_provision_build_tmp_dir }}/extra/templates"
      - "{{ _ce_provision_base_dir }}/config/templates"

- name: Add defaults lookup paths.
  set_fact:
    ce_provision_search_paths_template: "{{ ce_provision_search_paths_template + [ item + '/templates' ] }}"
  with_items: "{{ ansible_search_path }}"
