---
- name: Set "tracking" file for the playbook.
  set_fact:
    current_play_md5_file: "{{ _ce_provision_build_id }}-{{ playbook_dir | basename }}-{{ inventory_hostname }}"

- name: Sanitize tracking file name.
  set_fact:
    current_play_md5_file: "{{ current_play_md5_file | regex_replace('[^A-z0-9]', '') }}"

- name: Make sure file exists.
  copy:
    content: ""
    dest: "{{ _ce_provision_data_dir }}/{{ current_play_md5_file }}"
    force: false
    mode: "0666"
  delegate_to: localhost

- name: Compute current playbook md5
  shell: 'find {{ playbook_dir }} -type f -exec md5sum {} \; | cut -d " " -f1 | md5sum'
  args:
    warn: false
  delegate_to: "localhost"
  register: current_play_dir_md5

- name: Lookup current playbook md5
  set_fact:
    previous_play_dir_md5: "{{ lookup('file', '{{ _ce_provision_data_dir }}/{{ current_play_md5_file }}' ) }}"

- meta: end_play
  when:
    - current_play_dir_md5.stdout == previous_play_dir_md5
    - not _ce_provision_force_play

# @todo This should be removed/refactored
- name: Ensure /opt/bin directory exists.
  file:
    path: "/opt/bin"
    state: directory

- name: Load custom vars file.
  include_tasks: allowed_vars.yml
  when:
    - ce_provision.extra_repository
    - ce_provision.extra_repository_vars_file
    - ce_provision.extra_repository_allowed_vars
