---

  - name: Randomize root password.
    user:
      name: root
      state: present
      password: "{{ lookup('password', '/dev/null') | password_hash('sha512', lookup('password', '/dev/null')) }}"

  - name: Ensure /opt/bin directory exists.
    file:
      path: "/opt/bin"
      state: directory
  
  - name: Clone custom extra directory.
    local_action:
      module: git
      repo: "{{ ansible_provision.extra_repository }}"
      dest: "{{ _ansible_provision_build_tmp_dir }}/extra"
      version: "{{ ansible_provision.extra_repository_branch }}"
    when: ansible_provision.extra_repository

  - name: Include custom variables.
    include_vars:
      file: "{{ _ansible_provision_build_tmp_dir }}/extra/{{ ansible_provision.extra_repository_vars_file }}"
      name: _ansible_provision_extra_vars
    when: 
      - ansible_provision.extra_repository
      - ansible_provision.extra_repository_vars_file
  
  - name: Filter allowed custom variables.
    set_fact:
      ansible_provision_extra_vars_filtered: "{{ _ansible_provision_extra_vars | allowed_vars(ansible_provision.extra_repository_allowed_vars) }}"
    when:
      - ansible_provision.extra_repository
      - ansible_provision.extra_repository_vars_file
      - ansible_provision.extra_repository_allowed_vars

  - name: Override variables with custom ones.
    set_fact:
      "{{ item.name }}": "{{ ansible_provision_extra_vars_filtered[item.name] }}"
    when:
      - ansible_provision_extra_vars_filtered is defined
      - ansible_provision_extra_vars_filtered[item.name] is defined
    loop: "{{ ansible_provision.extra_repository_allowed_vars }}"

  - name: Define template lookup paths.
    set_fact:
      ansible_provision_search_paths_template: 
        - "{{ playbook_dir}}/templates"
        - "{{ _ansible_provision_build_tmp_dir }}/extra/templates"
        - "{{ _ansible_provision_base_dir }}/config/templates"
        - ""