---

  - name: Set "tracking" file for the playbook.
    set_fact:
      current_play_md5_file: "{{ _ansible_provision_build_id }}-{{ playbook_dir | basename }}"
  
  - name: Sanitize tracking file name.
    set_fact:
      current_play_md5_file: "{{ current_play_md5_file | regex_replace('[^A-z0-9]', '') }}"

  - name: Make sure file exists.
    local_action:  
      module: copy
      content: ""
      dest: "{{ _ansible_provision_data_dir }}/{{ current_play_md5_file }}"
      force: no
  
  - name: Compute current playbook md5
    shell: 'find {{ playbook_dir }} -type f -exec md5sum {} \; | cut -d " " -f1 | md5sum'
    args:
      warn: no
    delegate_to: 'localhost'
    register: current_play_dir_md5
    
  - name: Lookup current playbook md5
    set_fact:
      previous_play_dir_md5: "{{ lookup('file', '{{ _ansible_provision_data_dir }}/{{ current_play_md5_file }}' ) }}"
  
  - meta: end_play
    when: 
      - current_play_dir_md5.stdout == previous_play_dir_md5
      - not _ansible_provision_force_play

  # - name: Randomize root password.
  #   user:
  #     name: root
  #     state: present
  #     password: "*"

  # - name: Ensure /opt/bin directory exists.
  #   file:
  #     path: "/opt/bin"
  #     state: directory
  
  - name: Clone custom extra directory.
    local_action:
      module: git
      repo: "{{ ansible_provision.extra_repository }}"
      dest: "{{ _ansible_provision_build_tmp_dir }}/extra"
      version: "{{ ansible_provision.extra_repository_branch }}"
    when: ansible_provision.extra_repository

  - name: Include custom variables.
    include_vars:
      file: "{{ _ansible_provision_build_tmp_dir }}/extra/{{ ansible_provision.extra_repository_vars_file }}"
      name: _ansible_provision_extra_vars
    when: 
      - ansible_provision.extra_repository
      - ansible_provision.extra_repository_vars_file
  
  - name: Filter allowed custom variables.
    set_fact:
      ansible_provision_extra_vars_filtered: "{{ _ansible_provision_extra_vars | allowed_vars(ansible_provision.extra_repository_allowed_vars) }}"
    when:
      - ansible_provision.extra_repository
      - ansible_provision.extra_repository_vars_file
      - ansible_provision.extra_repository_allowed_vars

  - name: Override variables with custom ones.
    set_fact:
      "{{ item.name }}": "{{ ansible_provision_extra_vars_filtered[item.name] }}"
    when:
      - ansible_provision_extra_vars_filtered is defined
      - ansible_provision_extra_vars_filtered[item.name] is defined
    loop: "{{ ansible_provision.extra_repository_allowed_vars }}"

  - name: Define template lookup paths.
    set_fact:
      ansible_provision_search_paths_template: 
        - "{{ playbook_dir}}/templates"
        - "{{ _ansible_provision_build_tmp_dir }}/extra/templates"
        - "{{ _ansible_provision_base_dir }}/config/templates"
        - ""