---
- name: Ensure old pip versions are not installed.
  apt:
    pkg: ["python-pip"]
    state: absent

- name: Ensure pip3 is installed.
  apt:
    pkg: ["python3-pip", "python3-setuptools"]
    state: present
    update_cache: true
