---

- name: Ensure user .aws directory.
  file:
    path: "/home/{{ user_creds.user }}/.aws"
    recurse: yes
    owner: "{{ user_creds.user }}"
    group: "{{ user_creds.user }}"
    state: directory
  with_items: "{{ aws_credentials }}"
  loop_control:
    loop_var: user_creds

- name: Generate AWS credentials
  template:
    src: credentials.j2
    dest: "/home/{{ user_creds.user }}/.aws/credentials"
    owner: "{{ user_creds.user }}"
    group: "{{ user_creds.user }}"
  with_items: "{{ aws_credentials }}"
  loop_control:
    loop_var: user_creds
