---
# Install NodeJS
# @todo Should we use NVM instead ?.
- name: Add repository key for NodeJS repository.
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: Add repository for NodeJS.
  apt_repository: repo='deb https://deb.nodesource.com/node_{{ nodejs.version }} buster main' state=present

- name: Add source repository for NodeJS.
  apt_repository: repo='deb-src https://deb.nodesource.com/node_{{ nodejs.version }} buster main' state=present

- name: Add repository key for Yarn repository.
  apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg state=present

- name: Add repository for Yarn.
  apt_repository: repo='deb https://dl.yarnpkg.com/debian/ stable main' state=present

- name: Pin Node packages.
  template:
    src: nodesource.pref.j2
    dest: "/etc/apt/preferences.d/nodesource.pref"
    owner: root
    group: root
    mode: 0644
    force: true

- name: Update apt cache.
  apt:
    update_cache: true

- name: Ensure NodeJS is installed.
  apt:
    pkg: ["nodejs", "yarn"]
    state: present
    update_cache: true
