gitlab:
  server_name: provision-privileged.local
  ssl:
    handling: selfsigned
  ldap: no
haproxy:
  template: "haproxy-ssl-passthru"
  backends:
    - name: gitlab
      ip: 127.0.0.1
      port: 8881
      domain: "provision-privileged.local"
