---
aws_cloudwatch_agent:
  # Stream name.
  log_stream_name: "example"
  # You'd normally use IAM policies, but that allows
  # non-AWS servers to log in cloudwatch too.
  use_credentials: false
  credentials:
    aws_access_key_id: XXX
    aws_secret_access_key: XXX
    region: "eu-west-3"
