---
- name: Generate inbound rules
  ufw:
    port: "{{ inbound.port }}"
    from_ip: "{{ item }}"
    rule: allow
    direction: in
    proto: "{{ inbound.proto | default(omit) }}"
    comment: "{{ inbound.comment | default(omit) }}"
  with_items:
    - "{{ inbound.ips }}"
