---
- name: Generate outbound rules
  ufw:
    port: "{{ outbound.port }}"
    to_ip: "{{ item }}"
    rule: allow
    direction: out
    proto: "{{ outbound.proto | default(omit) }}"
    comment: "{{ outbound.comment | default(omit) }}"
  with_items:
    - "{{ outbound.ips }}"
