---

- name: Ensure mariadb-client is installed.
  apt:
    pkg: ["mariadb-client", "python-pymysql"]
    state: present
    update_cache: yes
    cache_valid_time: 240

- name: Copy debian.cnf credentials file.
  template:
    src: "mysql.creds.j2"
    dest: "/home/{{ user_deploy.username }}/.mysql.creds"
    owner: "{{ user_deploy.username }}"
    group: "{{ user_deploy.username }}"
    mode: 0600

- name: Trigger overrides
  include_role: 
    name: _overrides