- name: Construct private subnet name.
  set_fact:
    _aws_ec2_autoscale_cluster_private_subnet_name: "{{ aws_ec2_autoscale_cluster.name }}-{{ subnet.az }}"

- name: Construct private subnet definition.
  set_fact:
    _aws_ec2_autoscale_cluster_subnet_definition:
      name: "{{ _aws_ec2_autoscale_cluster_private_subnet_name }}"
      az: "{{ subnet.az }}"
      cidr_block: "{{ subnet.cidr_block }}"
      nat_ipv4: false
      assign_instances_ipv6: false

- name: Create private subnet.
  include_role:
    name: aws/aws_vpc_subnet
  vars:
    aws_vpc_subnet:
      aws_profile: "{{ aws_ec2_autoscale_cluster.aws_profile }}"
      region: "{{ aws_ec2_autoscale_cluster.region }}"
      vpc_id: "{{ _aws_ec2_autoscale_cluster_vpc_id }}"
      state: "{{ aws_ec2_autoscale_cluster.state }}"
      tags: "{{ aws_ec2_autoscale_cluster.tags }}"
      subnets:
        - "{{ _aws_ec2_autoscale_cluster_subnet_definition }}"

- name: Gather private subnet information
  ec2_vpc_subnet_info:
    profile: "{{ aws_ec2_autoscale_cluster.aws_profile }}"
    region: "{{ aws_ec2_autoscale_cluster.region }}"
    filters:
      vpc-id: "{{ _aws_ec2_autoscale_cluster_vpc_id }}"
      tag:Name: "{{ _aws_ec2_autoscale_cluster_private_subnet_name }}"
  register: _aws_ec2_autoscale_cluster_subnet

- name: Gather public subnet information
  ec2_vpc_subnet_info:
    profile: "{{ aws_ec2_autoscale_cluster.aws_profile }}"
    region: "{{ aws_ec2_autoscale_cluster.region }}"
    filters:
      vpc-id: "{{ _aws_ec2_autoscale_cluster_vpc_id }}"
      tag:Name: "{{ subnet.public_subnet }}"
  register: _aws_ec2_autoscale_cluster_public_subnet

- name: Add subnet id to the ids list.
  set_fact:
    _aws_ec2_autoscale_cluster_subnets_ids: "{{ _aws_ec2_autoscale_cluster_subnets_ids + [ _aws_ec2_autoscale_cluster_subnet.subnets[0].subnet_id ] }}"

- name: Add subnet to the list of EFS targets.
  set_fact:
    _aws_ec2_autoscale_cluster_efs_self_targets: "{{ _aws_ec2_autoscale_cluster_efs_self_targets + [ { 'subnet_id': _aws_ec2_autoscale_cluster_subnet.subnets[0].subnet_id, 'security_groups': [ _aws_ec2_autoscale_cluster_security_group.group_id ] } ] }}"

- name: Add subnet to the list of EFS targets.
  set_fact:
    _aws_ec2_autoscale_cluster_efs_targets: "{{ _aws_ec2_autoscale_cluster_efs_targets + [ { 'subnet_id': _aws_ec2_autoscale_cluster_subnet.subnets[0].subnet_id, 'security_groups': [ _aws_ec2_autoscale_cluster_existing_efs_security_group.security_groups[0].group_id ] } ] }}"

- name: Add public subnet to the list.
  set_fact:
    _aws_ec2_autoscale_cluster_public_subnets_ids: "{{ _aws_ec2_autoscale_cluster_public_subnets_ids + [ _aws_ec2_autoscale_cluster_existing_efs.efs[0].name ] }}"

# @todo Module has a bug and return result as a separate key.
- name: Gather NAT gateway info.
  ec2_vpc_nat_gateway_info:
    profile: "{{ aws_ec2_autoscale_cluster.aws_profile }}"
    region: "{{ aws_ec2_autoscale_cluster.region }}"
    filters:
      vpc-id: "{{ _aws_ec2_autoscale_cluster_vpc_id }}"
      tag:Name: "{{ subnet.public_subnet }}"
  register: _aws_ec2_autoscale_cluster_subnet_gateway

- name: Generate route table for the private subnet.
  include_role:
    name: aws/aws_vpc_route
  vars:
    aws_vpc_route:
      name: "{{ _aws_ec2_autoscale_cluster_private_subnet_name }}"
      aws_profile: "{{ aws_ec2_autoscale_cluster.aws_profile }}"
      region: "{{ aws_ec2_autoscale_cluster.region }}"
      vpc_id: "{{ _aws_ec2_autoscale_cluster_vpc_id }}"
      subnet_id: "{{ _aws_ec2_autoscale_cluster_subnet.subnets[0].subnet_id }}"
      tags: "{{ aws_ec2_autoscale_cluster.tags | combine( { 'Name': _aws_ec2_autoscale_cluster_private_subnet_name } ) }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ _aws_ec2_autoscale_cluster_subnet_gateway.result[0].nat_gateway_id }}"
