- name: Construct private subnet definition.
  set_fact:
    _aws_ec2_autoscale_cluster_subnet_definition:
      name: "{{ aws_ec2_autoscale_cluster.name }}-{{ subnet.az }}"
      az: "{{ subnet.az }}"
      cidr_block: "{{ subnet.cidr_block }}"
      nat_ipv4: yes
      assign_instances_ipv6: no

- name: Create private subnet.
  include_role:
    name: aws/aws_vpc_subnet
  vars:
    aws_vpc_subnet:
      aws_profile: "{{ aws_ec2_autoscale_cluster.aws_profile }}"
      region: "{{ aws_ec2_autoscale_cluster.region }}"
      vpc_id: "{{ _aws_ec2_autoscale_cluster_vpc_id }}"
      state: "{{ aws_ec2_autoscale_cluster.state }}"
      tags: "{{ aws_ec2_autoscale_cluster.tags }}"
      subnets:
        - "{{ _aws_ec2_autoscale_cluster_subnet_definition }}"

- name: Gather private subnet information
  ec2_vpc_subnet_info:
    profile: "{{ aws_ec2_autoscale_cluster.aws_profile }}"
    region: "{{ aws_ec2_autoscale_cluster.region }}"
    filters:
      vpc-id: "{{ _aws_ec2_autoscale_cluster_vpc_id }}"
      tag:Name: "{{ aws_ec2_autoscale_cluster.name }}-{{ subnet.az }}"
  register: _aws_ec2_autoscale_cluster_subnet

- name: Gather public subnet information
  ec2_vpc_subnet_info:
    profile: "{{ aws_ec2_autoscale_cluster.aws_profile }}"
    region: "{{ aws_ec2_autoscale_cluster.region }}"
    filters:
      vpc-id: "{{ _aws_ec2_autoscale_cluster_vpc_id }}"
      tag:Name: "{{ subnet.public_subnet }}"
  register: _aws_ec2_autoscale_cluster_public_subnet

- name: Add subnet id to the ids list.
  set_fact:
    _aws_ec2_autoscale_cluster_subnets_ids: "{{ _aws_ec2_autoscale_cluster_subnets_ids + [ _aws_ec2_autoscale_cluster_subnet.subnets[0].subnet_id ] }}"

- name: Add subnet to the list of EFS targets.
  set_fact:
    _aws_ec2_autoscale_cluster_efs_targets: "{{ _aws_ec2_autoscale_cluster_efs_targets + [ { 'subnet_id': _aws_ec2_autoscale_cluster_subnet.subnets[0].subnet_id } ] }}"

- name: Add public subnet to the list.
  set_fact:
    _aws_ec2_autoscale_cluster_public_subnets_ids: "{{ _aws_ec2_autoscale_cluster_public_subnets_ids + [ _aws_ec2_autoscale_cluster_public_subnet.subnets[0].subnet_id ] }}"