---

- name: Randomize root password.
  user:
    name: root
    state: present
    password: "{{ lookup('password', '/dev/null') | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"