---

- name: Randomize root password.
  user:
    name: root
    state: present
    password: "{{ lookup('password', '/dev/null') | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"

- name: Add authorized keys.
  authorized_key:
    user: root
    state: present
    key: "{{ key }}"
  with_items: "{{ user_root.authorized_keys }}"
  loop_control:
    loop_var: key

- name: Remove "admin" user.
  user:
    name: admin
    state: absent
    remove: yes
    force: yes
  when: user_root.delete_admin