---

- name: define SSL base path.
  set_fact:
    _ssl_base_path: '/etc/ssl/selfsigned'

- name: Create SSL directory.
  file:
    path: "{{ _ssl_base_path }}"
    state: directory

- name: define key path.
  set_fact:
    _ssl_current_key_path: "{{ _ssl_base_path }}/{{ ssl_selfsigned.domain }}.key"

- name: define cert path.
  set_fact:
    _ssl_current_cert_path: "{{ _ssl_base_path }}/{{ ssl_selfsigned.domain }}.cert"

- name: Check if we have an existing SSL key.
  stat:
    path: "{{ _ssl_current_key_path }}"
  register: ssl_key

- name: Generates a new key/cert.
  command: "openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj '/C=GB/ST=Test/L=London/O=CodeEnigma/OU=Test/CN={{ ssl_selfsigned.domain }}' -keyout {{ _ssl_current_key_path }} -out {{ _ssl_current_cert_path }}"
  when: not ssl_key.stat.exists

- name: Add key/cert pairs to know paths information.
  set_fact:
    _ssl_paths: "{{ _ssl_paths | combine({ ssl_selfsigned.domain:{ 'certificate': _ssl_current_cert_path, 'key': _ssl_current_key_path } }) }}"
      
