---
- name: Install PHP packages.
  apt:
    pkg:
      - "php{{ version }}-cli"
    state: present
  with_items: "{{ php.version }}"
  loop_control:
    loop_var: version

- name: Set php version (phar)
  command: "update-alternatives --set phar /usr/bin/phar{{ version }}"
  with_items: "{{ php.version }}"
  loop_control:
    loop_var: version

- name: Set php version (phar.phar)
  command: "update-alternatives --set phar.phar /usr/bin/phar.phar{{ version }}"
  with_items: "{{ php.version }}"
  loop_control:
    loop_var: version

- name: Set php version (php)
  command: "update-alternatives --set php /usr/bin/php{{ version }}"
  with_items: "{{ php.version }}"
  loop_control:
    loop_var: version

- name: Set php version (php-config)
  command: "update-alternatives --set php-config /usr/bin/php-config{{ version }}"
  with_items: "{{ php.version }}"
  loop_control:
    loop_var: version

- name: Copy php.ini for php cli.
  template:
    src: php.cli.ini.j2
    dest: "/etc/php/{{ version }}/cli/php.ini"
    force: yes
  with_items: "{{ php.version }}"
  loop_control:
    loop_var: version

- name: Setup xdebug.
  include_role:
    name: php_xdebug

- name: Setup composer.
  include_role:
    name: php_composer

- name: Trigger overrides
  include_role:
    name: _overrides
