---

- name: Add repository key for Jenkins.
  apt_key: url=https://pkg.jenkins.io/debian/jenkins.io.key state=present
  
- name: Add repository for Jenkins.
  apt_repository: repo='deb http://pkg.jenkins.io/debian-stable binary/' state=present

- name: Ensure Jenkins is installed.
  apt:
    pkg: "jenkins"
    state: present
    update_cache: yes
    
- name: Generates SSL keys.
  include_role:
    name: "{{ jenkins.ssl_handling }}"
  vars:
    ssl:
      domain: "{{ jenkins.server_name }}"
      services: []

- name: Check if we have an existing keystore.
  stat:
    path: "/var/lib/jenkins/{{ jenkins.server_name }}.jks"
  register: jenkins_keystore

- name: Convert SSL key to intermediate PK12.
  command: "openssl pkcs12 -export -out /dev/shm/jenkins_keystore.p12 -passout 'pass:{{ jenkins.keystore_pass }}' -inkey {{ _ssl_paths[jenkins.server_name].key }} -in {{ _ssl_paths[jenkins.server_name].certificate }} -name {{ jenkins.server_name }}"
  when: not jenkins_keystore.stat.exists

- name: Convert PK12 to keystore.
  command: "keytool -importkeystore -srckeystore /dev/shm/jenkins_keystore.p12 -srcstorepass '{{ jenkins.keystore_pass }}' -srcstoretype PKCS12 -srcalias {{ jenkins.server_name }} -deststoretype JKS -destkeystore /var/lib/jenkins/{{ jenkins.server_name }}.jks -deststorepass '{{ jenkins.keystore_pass }}' -destalias {{ jenkins.server_name }}"
  when: not jenkins_keystore.stat.exists

- name: Ensure keystore ownership.
  file:
    path: /var/lib/jenkins
    owner: "{{ jenkins.user }}"
    group: "{{ jenkins.user }}"
    recurse: true

- name: Ensure log ownership.
  file:
    path: /var/log/jenkins
    owner: "{{ jenkins.user }}"
    group: "{{ jenkins.user }}"
    recurse: true

- name: Ensure cache ownership.
  file:
    path: /var/cache/jenkins
    owner: "{{ jenkins.user }}"
    group: "{{ jenkins.user }}"
    recurse: true

- name: Copy Jenkins configuration file.
  template:
    src: "jenkins.j2"
    dest: /etc/default/jenkins

- name: Trigger overrides
  include_role: 
    name: _overrides

- name: Create init.groovy.d directory
  file:
    path: "/var/lib/jenkins/init.groovy.d"
    state: directory
    mode: '0755'

- name: Check if groovy security file exists    
  stat:
    path: "/var/lib/jenkins/init.groovy.d/basic-security.groovy"
  register: secinit

- name: Copy groovy security file
  template:
    src: "basic-security.groovy.j2"
    dest: "/var/lib/jenkins/init.groovy.d/basic-security.groovy"
    owner: "{{ jenkins.user }}"
    group: "{{ jenkins.user }}"
    mode: 0775

- name: restart jenkins
  service:
    name: jenkins
    state: restarted
  when: not secinit.stat.exists

- pause:
    minutes: 1
  when: not secinit.stat.exists

- name: Install Jenkins cert renewal script
  template:
    src: "jenkins-cert-renewal.j2"
    dest: "/usr/local/bin/jenkins-cert-renewal"
    owner: root
    group: root
    mode: 0775

- name: Add Jenkins cert renewal job
  lineinfile:
    path: '/etc/cron.d/certbot'
    line: "{{ jenkins.schedule }} {{ jenkins.user }}  /usr/local/bin/jenkins-cert-renewal 2> /dev/null"
    insertafter: EOF

- name: Install or Update Jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    jenkins_home: "/var/lib/jenkins"
    url_username: "{{ jenkins.adminuser }}"
    url_password: "{{ jenkins.adminpass }}"
    state: "present"
    timeout: "30"
    updates_expiration: "86400"
    updates_url: "https://updates.jenkins.io"
    url: "https://{{ jenkins.server_name }}"
    validate_certs: "no"
    with_dependencies: "yes"
  with_items: "{{ jenkins.plugins }}"
  notify: restart jenkins
