aws_iam_saml:
  aws_account_alias: ""
  provider_name: "SAMLProvider"
  admin_role: "Administrators"
  admin_ldap_groups: []
  readonly_role: "ReadOnly"
  readonly_ldap_groups: []
  billing_role: "Billing"
  billing_policy: "BillingPolicy"
  billing_ldap_groups: []
  saml_metadata_document: ""
  linotp_server: ""
  saml_repository: ""
  saml_repository_directory: "simplesamlphp"
  saml_repository_branch: "master"
  saml_include_path: ""
  saml_sp_path: ""
  saml_sp_certificate: ""