---
- name: Ensure xdebug is not installed.
  apt:
    pkg: php-xdebug
    state: absent
    purge: true
  when:
    - not xdebug.cli
    - not xdebug.fpm

- name: Remove trace output folder.
  file:
    path: "{{ xdebug.trace_output_dir }}"
    state: absent
  when:
    - not xdebug.cli
    - not xdebug.fpm

- name: Remove profiler output folder.
  file:
    path: "{{ xdebug.profiler_output_dir }}"
    state: absent
  when:
    - not xdebug.cli
    - not xdebug.fpm

- name: Ensure xdebug is installed.
  apt:
    pkg: php-xdebug
    state: present
    update_cache: true
    cache_valid_time: 240
  when: xdebug.cli or xdebug.fpm

- name: Create trace output folder.
  file:
    path: "{{ xdebug.trace_output_dir }}"
    state: directory
  when: xdebug.cli or xdebug.fpm

- name: Create profiler output folder.
  file:
    path: "{{ xdebug.profiler_output_dir }}"
    state: directory
  when: xdebug.cli or xdebug.fpm

- name: Set remote host (Default)
  set_fact:
    xdebug.remote_host: "127.0.0.1"
  when:
    - xdebug.remote_host == 'auto'

- name: Enable xdebug connect back (Default)
  set_fact:
    xdebug.remote_connect_back: "1"
  when:
    - xdebug.remote_host == 'auto'

- name: Set remote host (Docker for Mac)
  set_fact:
    xdebug.remote_host: "docker.for.mac.localhost"
  when:
    - xdebug.remote_host == "auto"
    - ce_dev_host_platform is defined
    - ce_dev_host_platform == "darwin"

- name: Disable xdebug connect back (Docker for Mac)
  set_fact:
    xdebug.remote_connect_back: "0"
  when:
    - xdebug.remote_connect_back == 'auto'
    - ce_dev_host_platform is defined
    - ce_dev_host_platform == "darwin"

- name: Copy xdebug configuration in place.
  template:
    src: 30-xdebug-dev.ini.j2
    dest: "/etc/php/{{ php.version }}/cli/conf.d/30-xdebug-dev.ini"
    owner: root
    group: root
    mode: "0644"
  when: xdebug.cli

- name: Copy xdebug configuration in place.
  template:
    src: 30-xdebug-dev.ini.j2
    dest: "/etc/php/{{ php.version }}/fpm/conf.d/30-xdebug-dev.ini"
    owner: root
    group: root
    mode: "0644"
  when: xdebug.fpm
