---
- name: Ensure old Ansible versions are not installed.
  apt:
    pkg: ["ansible"]
    state: absent

- name: Remove old repository key for Ansible.
  apt_key:
    id: 93C4A3FD7BB9C367
    keyserver: keyserver.ubuntu.com
    state: absent

- name: Remove old repository for Ansible.
  apt_repository:
    repo: "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main"
    state: absent

- name: Ensure Ansible dependencies are installed.
  apt:
    pkg: ["python-pip", "yamllint"]
    state: present
    update_cache: true

- name: Install Ansible.
  command:
    cmd: sudo pip install ansible
  become: false

- name: Install ansible-lint.
  command:
    cmd: pip install ansible-lint
  become: false
