---
- name: Remove old PPA repository key for Ansible.
  apt_key:
    id: 93C4A3FD7BB9C367
    keyserver: keyserver.ubuntu.com
    state: absent

- name: Remove old repository for Ansible.
  apt_repository:
    repo: "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main"
    state: absent

- name: Ensure Ansible is not installed by pip.
  command:
    cmd: sudo pip uninstall ansible
  become: false

- name: Ensure old boto versions are not installed.
  apt:
    pkg: ["python-botocore", "python-urllib3", "python-pip"]
    state: absent

- name: Ensure Ansible dependencies are installed.
  apt:
    pkg: ["python3-pip", "yamllint"]
    state: present
    update_cache: true

# Not using 'apt' - this needs to be one task or we break controller servers acting on themselves.
- name: Remove and re-install Ansible.
  command:
    cmd: sudo apt-get -y remove ansible && sudo pip3 install ansible
  become: false

- name: Install ansible-lint.
  command:
    cmd: pip3 install ansible-lint
  become: false
