---
- name: Create the system group.
  group:
    name: "{{ user_ansible.username }}"
    system: true

- name: Create additional groups.
  group:
    name: "{{ group }}"
    state: present
    system: true
  with_items: "{{ user_ansible.groups }}"
  loop_control:
    loop_var: group
  when: user_ansible.groups | length

- name: Create the system user.
  user:
    name: "{{ user_ansible.username }}"
    shell: /bin/bash
    group: "{{ user_ansible.username }}"
    uid: "{{ user_ansible.uid | default(omit) }}"
    system: true
    create_home: true
    home: "/home/{{ user_ansible.username }}"
    password: "*"
    groups: "{{ user_ansible.groups }}"

- name: Add user to sudoers.
  template:
    src: "sudoer.j2"
    dest: "/etc/sudoers.d/{{ user_ansible.username }}"
    owner: root
    group: root
    mode: "0600"
  when: user_ansible.sudoer

- name: Create an .ssh folder.
  file:
    path: "/home/{{ user_ansible.username }}/.ssh"
    state: directory
    owner: "{{ user_ansible.username }}"
    group: "{{ user_ansible.username }}"
    mode: "0700"

- name: Fetch public key from utility server.
  fetch:
    src: "/home/{{ user_ansible.utility_username }}/.ssh/id_rsa.pub"
    dest: "{{ _ce_provision_build_tmp_dir }}/authorized_keys"
    flat: true
  delegate_to: "{{ user_ansible.utility_host }}"

- name: Copy public key to target.
  copy:
    src: "{{ _ce_provision_build_tmp_dir }}/authorized_keys"
    dest: "/home/{{ user_ansible.username }}/.ssh/authorized_keys"
    owner: "{{ user_ansible.username }}"
    group: "{{ user_ansible.username }}"
    mode: "0644"
