---

user_deploy:
  # This sets both username and main group.
  username: "{% if is_local is defined and is_local %}ce-dev{% else %}deploy{% endif %}"
  # Local username of the deploy user.
  utility_username: "{% if is_local is defined and is_local %}ce-dev{% else %}deploy{% endif %}"
  sudoer: no