---
user_deploy:
  # This sets both username and main group.
  username: "{% if is_local is defined and is_local %}ce-dev{% else %}deploy{% endif %}"
  # Local username of the deploy user.
  utility_host: "localhost"
  utility_username: "{% if is_local is defined and is_local %}ce-dev{% else %}deploy{% endif %}"
  sudoer: false
  # List of additional groups to add the user to.
  groups: []
  keys: []
  # This determines if Drush should be installed during provisioning. Mainly used when servers run Drupal 7 sites.
  install_drush: false
  drush_version: 8.4.5
