---

- hosts: provision-controller
  become: yes
  vars:
    - domain_name: provision-controller.local
    - project_name: provision
    - env_type: dev
    - ansible_provision:
        username: "ce-dev"
        own_repository: "https://github.com/codeenigma/ansible-provision.git"
        own_repository_branch: "1.x"
        config_repository: "https://github.com/codeenigma/ansible-provision-config-example.git"
        config_repository_branch: "master"
        local_dir: "/home/ce-dev/ansible-provision"
  tasks:
    - import_role:
        name: ansible_provision