---
- hosts: provision-controller
  become: yes
  vars_files:
    - common.yml
  vars:
    - domain_name: provision-controller.local
    - project_name: provision
    - apt_extra_packages:
        - yamllint
  tasks:
    - import_role:
        name: ce_provision
    - name: Remove example git hooks.
      file:
        path: "/home/ce-dev/ce-provision/.git/hooks"
        state: absent
    - name: Create git-hooks link.
      file:
        src: "../git-hooks"
        dest: "/home/ce-dev/ce-provision/.git/hooks"
        state: link
