- name: Gather security group info.
  ec2_group_info:
    profile: "{{ aws_rds.aws_profile }}"
    region: "{{ aws_rds.region }}"
    filters:
      group_name: "{{ security_group }}"
      vpc_id: "{{ _aws_rds_rds_subnet_group.subnet_group.vpc_id }}"
  register: _aws_rds_security_group_info

- name: Add security group id.
  set_fact:
    _aws_rds_security_group_ids: "{{ _aws_rds_security_group_ids + [ _aws_rds_security_group_info.security_groups[0].group_id ] }}"
