---
# tasks file for clamav

- name: Ensure ClamAV packages are installed
  apt:
    pkg: ["clamav"]
    state: present
    update_cache: yes
    cache_valid_time: 240

- name: Copy clamscan report config
  template:
    src: "clamscan-report.j2"
    dest: "/usr/local/bin/clamscan-report"
    owner: root
    group: root
    mode: 0700

- name: Copy clamscan cron config
  template:
    src: "clamscan-cron.j2"
    dest: "/etc/cron.d/clamscan_cron"
    owner: root
    group: root
    mode: 0644
