---
- name: Ensure memcached is installed.
  apt:
    pkg: memcached
    state: present

- name: Copy memcached configuration in place.
  template:
    src: memcached.conf.j2
    dest: "/etc/memcached.conf"
    owner: root
    group: root
    mode: 0644

- name: Trigger overrides
  include_role:
    name: _overrides

- name: Ensure memcached is restarted
  service:
    name: memcached
    state: restarted
    enabled: yes
