- name: Add subnet to the list of EFS targets.
  set_fact:
    _aws_efs_targets: "{{ _aws_efs_targets | combine( { append: { 'subnet_id': append.subnet_id, 'ip_address': append.ip_address , 'security_groups': _aws_efs_security_group_ids + append.security_groups } } ) }}"
