name: Run tests

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  run-tests:
    # Name the Job
    name: Run tests against Ansible code base
    # Set the type of machine to run on
    runs-on: ubuntu-16.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the ansible-lint action (Super-Linter is too heavy)
      - name: Lint Ansible playbooks
        uses: ansible/ansible-lint-action@v4.1.0
        with:
          targets: ""

      - name: Documentation (build)
        if: ${{ always() }}
        run: contribute/toc.sh
        shell: bash

      - name: Documentation (check)
        if: ${{ always() }}
        run: '[ -z "$(git diff)" ] && [ -z "$( git ls-files . --exclude-standard --others)" ]'
        shell: bash

      - name: Run a test
        if: ${{ always() }}
        run: |
          wget https://golang.org/dl/go1.15.8.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.15.8.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          git clone https://github.com/FiloSottile/mkcert && cd mkcert
          go build -ldflags "-X main.Version=$(git describe --tags)"
          sudo mv ./mkcert /usr/local/bin && cd ../
          sudo chmod +x /usr/local/bin/mkcert
          curl -sL https://raw.githubusercontent.com/codeenigma/ce-dev/1.x/install.sh | /bin/sh -s -- linux
          git clone --branch 1.x https://github.com/codeenigma/ce-dev-ce-provision-config.git config
          /bin/bash ce-dev/ansible/examples/test.sh
        shell: bash

      - name: Documentation (push)
        if: ${{ contains(github.ref, '1.x') }}
        run: 'echo "On the release branch, we will build docs!"'
        shell: bash
